# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banking_system.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62\x61nking_system.proto\x12\x0e\x62\x61nking_system\"R\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x05\x12\x19\n\x11logical_timestamp\x18\x04 \x01(\x03\"Y\n\x08Response\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\x12\x0e\n\x06result\x18\x03 \x01(\t\x12\x19\n\x11logical_timestamp\x18\x04 \x01(\x03\x32U\n\x11\x65xchange_messages\x12@\n\x0bMsgDelivery\x12\x17.banking_system.Request\x1a\x18.banking_system.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banking_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=40
  _globals['_REQUEST']._serialized_end=122
  _globals['_RESPONSE']._serialized_start=124
  _globals['_RESPONSE']._serialized_end=213
  _globals['_EXCHANGE_MESSAGES']._serialized_start=215
  _globals['_EXCHANGE_MESSAGES']._serialized_end=300
# @@protoc_insertion_point(module_scope)
